config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "transactions#transfer"
  get '/transfer',   to: 'transactions#transfer'
  resources :transactions, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/entity.rb
require 'active_support/concern'
module Entity # TODO change name to something that make more sense
  extend ActiveSupport::Concern

  included do
    validates :name, presence: true, uniqueness: true

    has_one :wallet, as: :walletable, dependent: :destroy
    has_many :transactions, through: :wallet
    after_create :create_wallet
  end

  def withdrawal(wallet, amount)
    wallet.debits.create(recipient_wallet_id: wallet.id, amount: amount)
  end

  def deposit(wallet, amount)
    wallet.credits.create(sender_wallet_id: wallet.id, amount: amount)
  end
end

app/models/credit.rb
class Credit < Transaction # deposit
   # good for validations in scenario when someone want to deposit
end

app/models/debit.rb
class Debit < Transaction
# good for validations in scenario when someone want to withdraw and there is not enough amount
end

app/models/stock.rb
class Stock < ApplicationRecord
  include Entity
end

app/models/team.rb
class Team < ApplicationRecord
  include Entity
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  validates :amount, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 10000 }
  belongs_to :wallet
  after_create :update_wallet_balance

  def update_wallet_balance
    wallet.update_balance!
  end

  def initial_amount?
    recipient_wallet_id.nil? && sender_wallet_id.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Entity
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :walletable, polymorphic: true

  has_many :transactions, dependent: :destroy
  has_many :debits
  has_many :credits

  def update_balance!
    new_balance = calculate_new_balance
    update(balance: new_balance)
  end

  private

  def calculate_new_balance
    credits.sum(:amount) - debits.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :find_sender, only: :create
  before_action :find_recipient, only: :create

  def transfer
    @transaction = Transaction.new
  end

  def create
    if @sender != @recipient && @sender.wallet.balance >= params[:amount].to_f
      perform_transaction

      redirect_to transactions_path # TODO add some notice
    else
      render :transfer # TODO add alert based on condition that is not fullfil from 11 line 
    end
  end

  def index
    @transactions = Transaction.all
  end

  private

  def find_sender
    @sender = type_class(params[:sender_type]).find(params[:sender_id])
  end

  def find_recipient
    @recipient = type_class(params[:recipient_type]).find(params[:recipient_id])
  end

  def type_class(type)
    type.constantize
  end

  def perform_transaction
    ActiveRecord::Base.transaction do
      @sender.withdrawal(@recipient.wallet, params[:amount])
      @recipient.deposit(@sender.wallet, params[:amount])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raiza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<%= link_to "Transfer", transfer_path %>
<h1> Transactions</h1>

<% @transactions.each do |transaction| %>
  Id: <%= transaction.id %>
  Amount: <%= transaction.amount %>
  <% if transaction.initial_amount? %>
    initial_amount
  <% end %>

    Type:<%= transaction.type %>
  <br />
<% end %>

app/views/transactions/transfer.html.erb
<%= link_to "Transactions", transactions_path %>

<h1>Transfer page</h1>

<%= form_tag transactions_path @transfer do |f| %>

  <%= label_tag :amount %>
  <br/>
  <%= number_field_tag :amount %>

  <h3>Sender</h3>
  <div id="radioBtnSelectSender">
    <label data-attr="user">
      <%= radio_button_tag :sender_type, "User", checked: true %>User</label>
    <label data-attr="team">
      <%= radio_button_tag :sender_type, "Team" %>Team</label>
    <label data-attr="stock">
      <%= radio_button_tag :sender_type, "Stock" %>Stock</label>
  </div>
  <div class="form-group userDropDown">
    <%= label_tag :user %>
    <%= select_tag :sender_id, options_for_select(User.all.collect{ |u| [u.name, u.id] }), {required: true} %>
  </div>
  <div class="form-group teamDropDown">
    <%= label_tag :team %>
    <%= select_tag :sender_id, options_for_select(Team.all.collect{ |u| [u.name, u.id] }), {required: true, disabled: "disabled"} %>
  </div>
  <div class="form-group stockDropDown">
    <%= label_tag :stock %>
    <%= select_tag :sender_id, options_for_select(Stock.all.collect{ |u| [u.name, u.id] }), {required: true, disabled: "disabled"} %>
  </div>

  <h3>Recipient</h3>
  <div id="radioBtnSelectRecipient">
    <label data-attr="user">
      <%= radio_button_tag :recipient_type, "User", checked: true %>User</label>
    <label data-attr="team">
      <%= radio_button_tag :recipient_type, "Team" %>Team</label>
    <label data-attr="stock">
      <%= radio_button_tag :recipient_type, "Stock" %>Stock</label>
  </div>
  <div class="form-group userRecipientDropDown">
    <%= label_tag :user %>
    <%= select_tag :recipient_id, options_for_select(User.all.collect{ |u| [u.name, u.id] }), {required: true} %>
  </div>
  <div class="form-group teamRecipientDropDown">
    <%= label_tag :team %>
    <%= select_tag :recipient_id, options_for_select(Team.all.collect{ |u| [u.name, u.id] }), {required: true, disabled: "disabled"} %>
  </div>
  <div class="form-group stockRecipientDropDown">
    <%= label_tag :stock %>
    <%= select_tag :recipient_id, options_for_select(Stock.all.collect{ |u| [u.name, u.id] }), {required: true, disabled: "disabled"} %>
  </div>
  <br />

  <%= submit_tag "Transfer" %>

<% end %>